### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/sale#101]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] portal_sale_order_type
- [ ] sale_contract_editable
- [ ] sale_contract_restrict_domain
- [ ] sale_dummy_confirmation
- [ ] sale_exception_credit_limit
- [ ] sale_exception_partner_state
- [ ] sale_exception_price_security
- [ ] sale_exception_print
- [ ] sale_exceptions_ignore_approve
- [ ] sale_global_discount
- [ ] sale_global_three_discounts
- [ ] sale_invoice_operation
- [ ] sale_invoice_operation_line
- [ ] sale_order_line_number
- [ ] sale_order_type_automation
- [ ] sale_order_type_dummy_confirmation
- [ ] sale_order_type_invoice_policy
- [ ] sale_order_type_sequence
- [ ] sale_order_type_user_default
- [ ] sale_order_validity
- [ ] sale_price_update_margin
- [ ] sale_prices_update
- [ ] sale_procurement_date_confirm
- [ ] sale_quotation_products
- [ ] sale_require_contract
- [ ] sale_require_purchase_order_number
- [ ] sale_require_ref
- [ ] sale_restrict_partners
- [ ] sale_stock_availability
- [ ] sale_three_discounts
- [ ] sale_usability
- [ ] sale_usability_delivery
- [ ] sale_usability_return_invoicing
- [ ] sale_usability_stock
