### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/sale#220]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

- [x] event_sale_ux
- [x] portal_sale_distributor
- [ ] portal_sale_distributor_wesbite_quote
- [x] pos_ux
- [x] sale_delivery_ux
- [ ] sale_dummy_confirmation
- [x] sale_exception_credit_limit
- [x] sale_exception_partner_state
- [x] sale_exception_price_security
- [x] sale_exception_print
- [x] sale_exceptions_ignore_approve
- [x] sale_exceptions_timesheet
- [x] sale_margin_ux
- [x] sale_order_line_number
- [x] sale_order_lot_selection_ux
- [x] sale_order_type_automation
- [x] sale_order_type_invoice_policy
- [ ] sale_order_type_user_default
- [ ] sale_order_type_ux - By @ValentinoDefelice - #234 
- [ ] sale_order_validity
- [ ] sale_quotation_products
- [ ] sale_report_last_sale
- [ ] sale_require_contract
- [ ] sale_require_purchase_order_number
- [ ] sale_require_ref
- [ ] sale_restrict_partners
- [ ] sale_stock_analytic
- [ ] sale_stock_availability
- [ ] sale_stock_ux
- [ ] sale_three_discounts
- [ ] sale_three_discounts_ux
- [ ] sale_timesheet_ux
- [x] sale_ux - By @nicomacr - #233
