### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/sale#307]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] sale_margin_ux
- [ ] event_sale_ux
- [ ] sale_order_lot_selection_ux
- [ ] sale_timesheet_ux
- [ ] sale_exceptions_ignore_approve
- [ ] sale_stock_ux
- [ ] sale_order_line_number
- [ ] sale_order_type_invoice_policy
- [ ] sale_exception_credit_limit
- [ ] sale_exception_print
- [ ] sale_require_ref
- [ ] sale_three_discounts_ux
- [ ] sale_require_purchase_order_number
- [ ] sale_order_validity
- [ ] sale_quotation_ux
- [ ] sale_three_discounts
- [ ] portal_sale_distributor_website_sale
- [ ] sale_exceptions_timesheet
- [ ] sale_barcode
- [ ] sale_stock_analytic
- [ ] pos_ux
- [ ] sale_quotation_products
- [ ] sale_order_type_user_default
- [ ] sale_report_last_sale
- [ ] sale_order_type_automation
- [ ] sale_exception_price_security
- [ ] sale_stock_availability
- [ ] ~~crm_ux~~ v13 already provides this functionality
- [ ] sale_exception_partner_state
- [ ] sale_require_contract
- [ ] sale_order_type_ux
- [ ] sale_ux
- [ ] sale_delivery_ux
- [ ] portal_sale_distributor
